server:
  port: 8090
# 公安算法接口地址
com:
  dinfo:
    algorithmUrl: http://58.17.133.80:18087/recordanalysis/app/theft-suspect
    # 交通类算法抽取接口
    trafficUrl: http://58.17.133.80:18087/recordanalysis/app/shunde-traffic

spring:
  datasource:
    username: root
    password: oec!Server
    url: jdbc:mysql://117.107.241.68:31306/interrogation?serverTimezone=GMT%2B8&charset=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    expire: 60
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql(打印SQL语句)
logging:
  level:
    com:
      dinfo:
        robotea:
          mapper: debug